### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by apple1417** [bl-sdk/PythonSDK#115]
The SDK codebase is a mess of code styles, since it's been passed between so many authors without proper standardization. We should define a standard, and format it to fix.

Tracking:
- [x] Decide on convention and create config for editorconfig/clang format/others
- [ ] C++ Code formatting
  - [ ] Github check for formatting
- [ ] One class/module per file
- [ ] Document all functions/types
  - [ ] Github check for documentation

**Comment by apple1417** [comment]
Looking at the following `.clang-format`
```yml
---
Language:        Cpp
BasedOnStyle:    Chromium
ColumnLimit:     100
SortIncludes:    CaseInsensitive
UseTab:          ForContinuationAndIndentation
IndentWidth:     4
TabWidth:        4
InsertBraces:    true
---
```
Visual studio can pull settings from this file, so we don't need a separate `.editorconfig`.

`InsertBraces` relies on clang format version 15, the first release candidate of which is coming out shortly. This issue is on hold until then.
